---
title: "Drawing DAGs: trees and heat-related illness"
author-meta: "Jesse Brunner"
date-meta: "`r Sys.Date()`"
format:
  pdf: default
  html: 
    self-contained: true
    grid:
      margin-width: 350px
format-links: false
execute:
  echo: false
toc: false
reference-location: margin
---


# Is urban forestry public health?
In his piece, [How Public Health Took Part in Its Own Downfall](https://wsu.instructure.com/courses/1798880/files/137018618), Ed Yong makes the case that public health should be viewed quite broadly. He didn't say this, but I think you could extend his argument to the idea that urban forestry, the planting of trees in towns and cities, could be viewed as an aspect of public health. Excess heat can cause mortality directly and indirectly, as well as simply exacerbate existing health issues. The several other readings about trees discuss their importance in reducing heat for local communities as well as their unequal distribution. [Tim Hartford's story](https://omny.fm/shows/cautionary-tales-with-tim-harford/chicago-when-it-sizzles) about a Chicago heatwave emphasized the importance of trust and community in responding to heat waves. And of course Given all of this, I would like you to...


# Draw a DAG about the factors that influence heat-related illness and deaths

\vspace{7cm}

# Use your DAG as a tool

Now, imagine you are responsible for the public health of a metropolitan area that is expected to face more and more severe heat waves. Given your understanding of causation in this system, which 1--2 things would you try to change? Based on your DAG, what advantages or problems might you face?

